### ISSUE TITLE
Missing the implementation of the function, MathOptInterface.VectorAffineFunction.

### ISSUE THREAD

**Issue by yim0331** [JuliaOpt/Dualization.jl#75] opened 2020-01-15 22:21 UTC
A overload function for MathOptInterface.VectorAffineFunction looks not implemented.
I'm having the following error message while using the Dualization package:

`ERROR: LoadError: Constraints of funtion MathOptInterface.VectorAffineFunction{Float64} in the Set MathOptInterface.PositiveSemidefiniteConeSquare are not implemented`
`Stacktrace:`
` [1] error(::String, ::Type, ::String, ::Type, ::String) at .\error.jl:42`
 `[2] supported_constraints(::Array{Tuple{DataType,DataType},1}) at C:\Users\yim\.julia\packages\Dualization\VTZt0\src\supported.jl:9`
` [3] dualize(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::Dualization.DualProblem{Float64,MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::Dualization.DualNames, ::Array{MathOptInterface.VariableIndex,1}, ::Bool) at C:\Users\yim\.julia\packages\Dualization\VTZt0\src\dualize.jl:27`
 `[4] #dualize#2 at C:\Users\yim\.julia\packages\Dualization\VTZt0\src\dualize.jl:16 [inlined]`
` [5] (::getfield(Dualization, Symbol("#kw##dualize")))(::NamedTuple{(:dual_names,),Tuple{Dualization.DualNames}}, ::typeof(Dualization.dualize), ::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::Dualization.DualProblem{Float64,MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}) at .\none:0`
 `[6] #dualize#3(::Dualization.DualNames, ::typeof(Dualization.dualize), ::Model) at C:\Users\yim\.julia\packages\Dualization\VTZt0\src\dualize.jl:77`

**Comment by odow** [comment] 2020-01-15 22:51
Duplicate of #73. See the discussion in that issue.

**Closed by odow** 2020-01-15 22:51 UTC
